import { MetroLine, MetroNetwork, MetroStation } from './types';

/**
 * Namma Metro (Bengaluru) — Purple, Green, Yellow.
 * Coordinates are approximate station centres for offline GPS guidance.
 */
const stationsList: MetroStation[] = [
  // —— Purple (Whitefield → Challaghatta) ——
  { id: 'whitefield', name: 'Whitefield (Kadugodi)', shortName: 'Whitefield', lat: 12.9698, lng: 77.7499, lines: ['purple'] },
  { id: 'hopefarm', name: 'Hopefarm Channasandra', shortName: 'Hopefarm', lat: 12.9864, lng: 77.7412, lines: ['purple'] },
  { id: 'kadugodi_tp', name: 'Kadugodi Tree Park', shortName: 'Kadugodi TP', lat: 12.9906, lng: 77.7278, lines: ['purple'] },
  { id: 'pattandur', name: 'Pattandur Agrahara', shortName: 'Pattandur', lat: 12.9928, lng: 77.7164, lines: ['purple'] },
  { id: 'sss_hospital', name: 'Sri Sathya Sai Hospital', shortName: 'SSS Hospital', lat: 12.9942, lng: 77.7051, lines: ['purple'] },
  { id: 'nallurhalli', name: 'Nallurhalli', shortName: 'Nallurhalli', lat: 12.9955, lng: 77.6948, lines: ['purple'] },
  { id: 'kundalahalli', name: 'Kundalahalli', shortName: 'Kundalahalli', lat: 12.9689, lng: 77.7156, lines: ['purple'] },
  { id: 'seetharampalya', name: 'Seetharampalya', shortName: 'Seetharampalya', lat: 12.9782, lng: 77.7084, lines: ['purple'] },
  { id: 'hoodi', name: 'Hoodi', shortName: 'Hoodi', lat: 12.9921, lng: 77.7159, lines: ['purple'] },
  { id: 'garudacharapalya', name: 'Garudacharapalya', shortName: 'Garudacharapalya', lat: 12.9995, lng: 77.7032, lines: ['purple'] },
  { id: 'singayyanapalya', name: 'Singayyanapalya', shortName: 'Singayyanapalya', lat: 13.0048, lng: 77.6941, lines: ['purple'] },
  { id: 'kr_puram', name: 'Krishnarajapura', shortName: 'KR Puram', lat: 13.0169, lng: 77.6858, lines: ['purple'] },
  { id: 'baiyappanahalli', name: 'Baiyappanahalli', shortName: 'Baiyappanahalli', lat: 12.9908, lng: 77.6525, lines: ['purple'] },
  { id: 'sv_road', name: 'Swami Vivekananda Road', shortName: 'SV Road', lat: 12.9856, lng: 77.6412, lines: ['purple'] },
  { id: 'indiranagar', name: 'Indiranagar', shortName: 'Indiranagar', lat: 12.9784, lng: 77.6408, lines: ['purple'] },
  { id: 'halasuru', name: 'Halasuru', shortName: 'Halasuru', lat: 12.9756, lng: 77.6268, lines: ['purple'] },
  { id: 'trinity', name: 'Trinity', shortName: 'Trinity', lat: 12.9730, lng: 77.6170, lines: ['purple'] },
  { id: 'mg_road', name: 'Mahatma Gandhi Road', shortName: 'MG Road', lat: 12.9756, lng: 77.6066, lines: ['purple'] },
  { id: 'cubbon_park', name: 'Cubbon Park', shortName: 'Cubbon Park', lat: 12.9770, lng: 77.5952, lines: ['purple'] },
  { id: 'vidhana_soudha', name: 'Vidhana Soudha', shortName: 'Vidhana Soudha', lat: 12.9794, lng: 77.5906, lines: ['purple'] },
  { id: 'central_college', name: 'Sir M. Visvesvaraya Central College', shortName: 'Central College', lat: 12.9818, lng: 77.5788, lines: ['purple'] },
  {
    id: 'majestic',
    name: 'Nadaprabhu Kempegowda Station, Majestic',
    shortName: 'Majestic',
    lat: 12.9766,
    lng: 77.5713,
    lines: ['purple', 'green'],
  },
  { id: 'city_railway', name: 'City Railway Station', shortName: 'City Railway', lat: 12.9778, lng: 77.5642, lines: ['purple'] },
  { id: 'magadi_road', name: 'Magadi Road', shortName: 'Magadi Road', lat: 12.9754, lng: 77.5550, lines: ['purple'] },
  { id: 'hosahalli', name: 'Hosahalli', shortName: 'Hosahalli', lat: 12.9742, lng: 77.5456, lines: ['purple'] },
  { id: 'vijayanagar', name: 'Vijayanagar', shortName: 'Vijayanagar', lat: 12.9714, lng: 77.5372, lines: ['purple'] },
  { id: 'attiguppe', name: 'Attiguppe', shortName: 'Attiguppe', lat: 12.9668, lng: 77.5304, lines: ['purple'] },
  { id: 'deepanjali_nagar', name: 'Deepanjali Nagar', shortName: 'Deepanjali Nagar', lat: 12.9612, lng: 77.5238, lines: ['purple'] },
  { id: 'mysuru_road', name: 'Mysuru Road', shortName: 'Mysuru Road', lat: 12.9538, lng: 77.5186, lines: ['purple'] },
  { id: 'nayandahalli', name: 'Pantharapalya - Nayandahalli', shortName: 'Nayandahalli', lat: 12.9456, lng: 77.5124, lines: ['purple'] },
  { id: 'rr_nagar', name: 'Rajarajeshwari Nagar', shortName: 'RR Nagar', lat: 12.9278, lng: 77.5206, lines: ['purple'] },
  { id: 'jnanabharathi', name: 'Jnanabharathi', shortName: 'Jnanabharathi', lat: 12.9412, lng: 77.5052, lines: ['purple'] },
  { id: 'pattanagere', name: 'Pattanagere', shortName: 'Pattanagere', lat: 12.9284, lng: 77.4988, lines: ['purple'] },
  { id: 'kengeri_bus', name: 'Kengeri Bus Terminal', shortName: 'Kengeri Bus', lat: 12.9146, lng: 77.4872, lines: ['purple'] },
  { id: 'kengeri', name: 'Kengeri', shortName: 'Kengeri', lat: 12.9078, lng: 77.4824, lines: ['purple'] },
  { id: 'challaghatta', name: 'Challaghatta', shortName: 'Challaghatta', lat: 12.8942, lng: 77.4688, lines: ['purple'] },

  // —— Green (Madavara → Silk Institute) ——
  { id: 'madavara', name: 'Madavara', shortName: 'Madavara', lat: 13.0812, lng: 77.4678, lines: ['green'] },
  { id: 'chikkabidarakallu', name: 'Chikkabidarakallu', shortName: 'Chikkabidarakallu', lat: 13.0724, lng: 77.4756, lines: ['green'] },
  { id: 'manjunathanagara', name: 'Manjunathanagara', shortName: 'Manjunathanagara', lat: 13.0648, lng: 77.4832, lines: ['green'] },
  { id: 'nagasandra', name: 'Nagasandra', shortName: 'Nagasandra', lat: 13.0486, lng: 77.5002, lines: ['green'] },
  { id: 'dasarahalli', name: 'Dasarahalli', shortName: 'Dasarahalli', lat: 13.0432, lng: 77.5118, lines: ['green'] },
  { id: 'jalahalli', name: 'Jalahalli', shortName: 'Jalahalli', lat: 13.0398, lng: 77.5214, lines: ['green'] },
  { id: 'peenya_industry', name: 'Peenya Industry', shortName: 'Peenya Industry', lat: 13.0336, lng: 77.5288, lines: ['green'] },
  { id: 'peenya', name: 'Peenya', shortName: 'Peenya', lat: 13.0284, lng: 77.5356, lines: ['green'] },
  { id: 'goraguntepalya', name: 'Goraguntepalya', shortName: 'Goraguntepalya', lat: 13.0228, lng: 77.5432, lines: ['green'] },
  { id: 'yeshwanthpur', name: 'Yeshwanthpur', shortName: 'Yeshwanthpur', lat: 13.0186, lng: 77.5564, lines: ['green'] },
  { id: 'sandal_soap', name: 'Sandal Soap Factory', shortName: 'Sandal Soap', lat: 13.0108, lng: 77.5602, lines: ['green'] },
  { id: 'mahalakshmi', name: 'Mahalakshmi', shortName: 'Mahalakshmi', lat: 13.0032, lng: 77.5628, lines: ['green'] },
  { id: 'rajajinagar', name: 'Rajajinagar', shortName: 'Rajajinagar', lat: 12.9956, lng: 77.5654, lines: ['green'] },
  { id: 'kuvempu_road', name: 'Mahakavi Kuvempu Road', shortName: 'Kuvempu Road', lat: 12.9898, lng: 77.5682, lines: ['green'] },
  { id: 'srirampura', name: 'Srirampura', shortName: 'Srirampura', lat: 12.9842, lng: 77.5704, lines: ['green'] },
  { id: 'sampige_road', name: 'Sampige Road', shortName: 'Sampige Road', lat: 12.9802, lng: 77.5710, lines: ['green'] },
  // majestic shared
  { id: 'chickpete', name: 'Chickpete', shortName: 'Chickpete', lat: 12.9698, lng: 77.5768, lines: ['green'] },
  { id: 'kr_market', name: 'Krishna Rajendra Market', shortName: 'KR Market', lat: 12.9618, lng: 77.5746, lines: ['green'] },
  { id: 'national_college', name: 'National College', shortName: 'National College', lat: 12.9524, lng: 77.5732, lines: ['green'] },
  { id: 'lalbagh', name: 'Lalbagh', shortName: 'Lalbagh', lat: 12.9468, lng: 77.5804, lines: ['green'] },
  { id: 'south_end', name: 'South End Circle', shortName: 'South End', lat: 12.9412, lng: 77.5868, lines: ['green'] },
  { id: 'jayanagar', name: 'Jayanagar', shortName: 'Jayanagar', lat: 12.9308, lng: 77.5836, lines: ['green'] },
  {
    id: 'rv_road',
    name: 'Rashtreeya Vidyalaya Road',
    shortName: 'RV Road',
    lat: 12.9256,
    lng: 77.5802,
    lines: ['green', 'yellow'],
  },
  { id: 'banashankari', name: 'Banashankari', shortName: 'Banashankari', lat: 12.9184, lng: 77.5738, lines: ['green'] },
  { id: 'jp_nagar', name: 'Jaya Prakash Nagar', shortName: 'JP Nagar', lat: 12.9078, lng: 77.5856, lines: ['green'] },
  { id: 'yelachenahalli', name: 'Yelachenahalli', shortName: 'Yelachenahalli', lat: 12.8972, lng: 77.5704, lines: ['green'] },
  { id: 'konanakunte', name: 'Konanakunte Cross', shortName: 'Konanakunte', lat: 12.8864, lng: 77.5688, lines: ['green'] },
  { id: 'doddakallasandra', name: 'Doddakallasandra', shortName: 'Doddakallasandra', lat: 12.8768, lng: 77.5612, lines: ['green'] },
  { id: 'vajarahalli', name: 'Vajarahalli', shortName: 'Vajarahalli', lat: 12.8684, lng: 77.5524, lines: ['green'] },
  { id: 'thalaghattapura', name: 'Thalaghattapura', shortName: 'Thalaghattapura', lat: 12.8602, lng: 77.5418, lines: ['green'] },
  { id: 'silk_institute', name: 'Silk Institute', shortName: 'Silk Institute', lat: 12.8478, lng: 77.5386, lines: ['green'] },

  // —— Yellow (RV Road → Bommasandra) ——
  { id: 'ragigudda', name: 'Ragigudda', shortName: 'Ragigudda', lat: 12.9204, lng: 77.5936, lines: ['yellow'] },
  { id: 'jayadeva', name: 'Jayadeva Hospital', shortName: 'Jayadeva', lat: 12.9168, lng: 77.6012, lines: ['yellow'] },
  { id: 'btm_layout', name: 'BTM Layout', shortName: 'BTM Layout', lat: 12.9142, lng: 77.6104, lines: ['yellow'] },
  { id: 'central_silk_board', name: 'Central Silk Board', shortName: 'Silk Board', lat: 12.9176, lng: 77.6228, lines: ['yellow'] },
  { id: 'bommanahalli', name: 'Bommanahalli', shortName: 'Bommanahalli', lat: 12.9084, lng: 77.6302, lines: ['yellow'] },
  { id: 'hongasandra', name: 'Hongasandra', shortName: 'Hongasandra', lat: 12.8968, lng: 77.6364, lines: ['yellow'] },
  { id: 'kudlu_gate', name: 'Kudlu Gate', shortName: 'Kudlu Gate', lat: 12.8842, lng: 77.6448, lines: ['yellow'] },
  { id: 'singasandra', name: 'Singasandra', shortName: 'Singasandra', lat: 12.8724, lng: 77.6522, lines: ['yellow'] },
  { id: 'hosa_road', name: 'Hosa Road', shortName: 'Hosa Road', lat: 12.8608, lng: 77.6614, lines: ['yellow'] },
  { id: 'beratena', name: 'Beratena Agrahara', shortName: 'Beratena', lat: 12.8486, lng: 77.6688, lines: ['yellow'] },
  { id: 'electronic_city', name: 'Electronic City', shortName: 'Electronic City', lat: 12.8398, lng: 77.6772, lines: ['yellow'] },
  { id: 'huskur_road', name: 'Huskur Road', shortName: 'Huskur Road', lat: 12.8304, lng: 77.6846, lines: ['yellow'] },
  { id: 'hebbagodi', name: 'Hebbagodi', shortName: 'Hebbagodi', lat: 12.8212, lng: 77.6924, lines: ['yellow'] },
  { id: 'bommasandra', name: 'Bommasandra', shortName: 'Bommasandra', lat: 12.8124, lng: 77.6988, lines: ['yellow'] },
];

const purpleOrder = [
  'whitefield',
  'hopefarm',
  'kadugodi_tp',
  'pattandur',
  'sss_hospital',
  'nallurhalli',
  'kundalahalli',
  'seetharampalya',
  'hoodi',
  'garudacharapalya',
  'singayyanapalya',
  'kr_puram',
  'baiyappanahalli',
  'sv_road',
  'indiranagar',
  'halasuru',
  'trinity',
  'mg_road',
  'cubbon_park',
  'vidhana_soudha',
  'central_college',
  'majestic',
  'city_railway',
  'magadi_road',
  'hosahalli',
  'vijayanagar',
  'attiguppe',
  'deepanjali_nagar',
  'mysuru_road',
  'nayandahalli',
  'rr_nagar',
  'jnanabharathi',
  'pattanagere',
  'kengeri_bus',
  'kengeri',
  'challaghatta',
];

const greenOrder = [
  'madavara',
  'chikkabidarakallu',
  'manjunathanagara',
  'nagasandra',
  'dasarahalli',
  'jalahalli',
  'peenya_industry',
  'peenya',
  'goraguntepalya',
  'yeshwanthpur',
  'sandal_soap',
  'mahalakshmi',
  'rajajinagar',
  'kuvempu_road',
  'srirampura',
  'sampige_road',
  'majestic',
  'chickpete',
  'kr_market',
  'national_college',
  'lalbagh',
  'south_end',
  'jayanagar',
  'rv_road',
  'banashankari',
  'jp_nagar',
  'yelachenahalli',
  'konanakunte',
  'doddakallasandra',
  'vajarahalli',
  'thalaghattapura',
  'silk_institute',
];

const yellowOrder = [
  'rv_road',
  'ragigudda',
  'jayadeva',
  'btm_layout',
  'central_silk_board',
  'bommanahalli',
  'hongasandra',
  'kudlu_gate',
  'singasandra',
  'hosa_road',
  'beratena',
  'electronic_city',
  'huskur_road',
  'hebbagodi',
  'bommasandra',
];

const lines: MetroLine[] = [
  {
    id: 'purple',
    name: 'Purple Line',
    color: '#7B2D8E',
    stations: purpleOrder,
  },
  {
    id: 'green',
    name: 'Green Line',
    color: '#1B8A3E',
    stations: greenOrder,
  },
  {
    id: 'yellow',
    name: 'Yellow Line',
    color: '#D4A017',
    stations: yellowOrder,
  },
];

const stations: Record<string, MetroStation> = {};
for (const s of stationsList) {
  stations[s.id] = s;
}

export const BANGALORE_METRO: MetroNetwork = {
  id: 'blr',
  name: 'Namma Metro',
  city: 'Bengaluru',
  operator: 'BMRCL',
  lines,
  stations,
};

export const BANGALORE_STATION_LIST = stationsList
  .slice()
  .sort((a, b) => a.name.localeCompare(b.name));
